Drop jQuery and migrate from Bootstrap 3 to 5
racketscript/racketscript-playground pull request #46
Opened 2023-05-30 20:53 UTC by leiDnedyA

WIP: Saving my progress here, but I still need to migrate the POST request done to save gists to the fetch API and get rid of some jQuery DOM queries in the colored carpet example.

2023-06-01 18:10 UTC, vishesh commented
Awesome! Thanks for doing this :)

2023-06-02 14:17 UTC, leiDnedyA commented
No problem, it's been fun to work on!

2023-06-05 19:11 UTC, stchang commented
First observations:
- font is smaller (too small?)
- glyphicons (the icons next to "log in", "compile", etc) are not showing up?
- "Overview" example not loading anything for me

2023-06-05 19:13 UTC, stchang commented on static/index.html
> +          <li class="nav-item"><a class="nav-link" href="#" id="btn-save" class="d-none"><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Save</a></li>
Looks like [`glyphicon`s are deprecated](https://stackoverflow.com/questions/32612690/bootstrap-4-glyphicons-migration)? Maybe replace with something suggested here instead? https://icons.getbootstrap.com/

2023-06-05 19:14 UTC, stchang commented on static/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" cr
Is there a reason to use an `alpha`? The [links here](https://getbootstrap.com/docs/5.3/getting-started/download/) might be more stable?

2023-06-05 19:48 UTC, stchang commented on examples/overview.rkt
> +($> (#js.document.addEventListener #js"DOMContentLoaded"
[`DOMContentLoaded` is not exactly the same as jquery `ready`](https://stackoverflow.com/questions/11523359/is-domcontentloaded-event-exactly-the-same-as-jquerys-ready-function). Maybe attach event to `window.document` instead of just `document`?

2023-06-06 16:10 UTC, leiDnedyA commented on static/index.html
> +          <li class="nav-item"><a class="nav-link" href="#" id="btn-save" class="d-none"><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Save</a></li>
According to [this stackoverflow post](https://stackoverflow.com/questions/32612690/bootstrap-4-glyphicons-migration#:~:text=You%20can%20still%20use%20glyphicons,be%20shipped%20with%20bootstrap%20anymore.), glyphicons aren't shipped with boostrap anymore, but instead of just adding a link to their CDN I replaced the icons with the bootstrap icons you suggested.

2023-06-06 16:14 UTC, leiDnedyA commented on static/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" cr
Good catch, I'll switch over to a standard release.

2023-06-07 17:07 UTC, leiDnedyA commented
I got the overview example up and running again with vanilla JS! Please feel free to review the new comments and formatting, but the code runs exactly like it did before.

2023-06-08 00:53 UTC, stchang commented on client.rkt
> +  (define (add-button-onclick button-id func)
I think this `add-button-onclick` function can be defined at the top-level?

2023-06-08 00:57 UTC, stchang commented on examples/overview.rkt
> +              (add-attr elem name val))
if you rearrange the order of `add-attr`'s parameters, then you can drop the `lambda` and just pass `add-attr` directly to `foldl`.

2023-06-08 00:58 UTC, stchang commented on examples/overview.rkt
> +             (add-child elem child))
can drop the lambda, as mentioned above, but here with `add-child`

2023-06-08 14:38 UTC, leiDnedyA commented on client.rkt
> +  (define (add-button-onclick button-id func)
Okay, I moved it to the top-level and reworked some of the variable names that it uses

2023-06-08 14:39 UTC, leiDnedyA commented on examples/overview.rkt
> +              (add-attr elem name val))
Good catch, I didn't notice that redundancy

2023-06-08 14:42 UTC, leiDnedyA commented on examples/overview.rkt
> +             (add-child elem child))
Implemented and tested this and the previous comment's suggestion in c262d55c39152b731aec193cc7577fe3add52834

2023-06-12 17:42 UTC, stchang requested changes

2023-06-12 17:42 UTC, stchang commented on client.rkt
> +                  [Content-type (js-string "application/json; charset=utf-8")]}]
fix indent

2023-06-12 17:42 UTC, stchang commented on client.rkt
> +        })
put all closing parens [with the last line of code](https://docs.racket-lang.org/style/Textual_Matters.html) (should not be on its own line)

2023-06-12 17:42 UTC, stchang commented on client.rkt
> +))
remove dangling close parens

2023-06-12 17:42 UTC, stchang commented on client.rkt
> +  )
fix closing parens

2023-06-12 17:42 UTC, stchang commented on client.rkt
> +)
fix closing parens

2023-06-12 17:42 UTC, stchang commented on client.rkt
> +                  [Content-type (js-string "application/json; charset=utf-8")]}]
fix indent

2023-06-12 17:42 UTC, stchang commented on client.rkt
> +)
more dangling closing parens (fix them all, won't add any more comments about it)

2023-06-12 19:51 UTC, leiDnedyA commented
I just went through and fixed all of the dangling parenthesis and indentation issues according to the [style guide,](https://docs.racket-lang.org/style/Textual_Matters.html) should be good now.

2023-06-13 16:07 UTC, stchang approved these changes

2023-06-13 16:08 UTC, merged